# Generated by Django 4.2.2 on 2023-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
